version: '3.8'

services:
  app_gu:
    container_name: app_gu
    image: laravel_app_gu
    restart: unless-stopped
    build:
      context: .
      # dockerfile: worker.dockerfile
    ports:
      - "8001:8001"
    # volumes:
    #   - .:/app
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
    networks:
      - docker_appnet

networks:
  docker_appnet:
    external: true  # ‚Üê karena jaringan sudah dibuat di luar compose
