version: '3.8'

services:
  laravel_franken:
    container_name: laravel_franken
    build: .
    image: image_laravel_franken
    ports:
      - "8080:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      
  db:
    container_name: mysql_laravel
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: gudang_umum
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8085:80"  # Port untuk phpMyAdmin di host
    environment:
      PMA_HOST: db  # Nama service MySQL di Docker Compose
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
